# These are supported funding model platforms

github: [joyinjoester]
ko_fi: joyinjoester
liberapay: JoyinJoester
custom: ['https://afdian.com/a/JoyinJoester','https://www.paypal.com/ncp/payment/BHSYWK73CA8FW']
