package takagi.ru.monica.ui.screens

import android.content.Context
import takagi.ru.monica.R
import takagi.ru.monica.navigation.Screen

/** Static, localized setting metadata only. Never indexes stored vault or account data. */
internal fun settingsSearchEntries(context: Context, isPlusActivated: Boolean = false): List<SettingsSearchEntry> {
    fun entry(title: Int, route: String, path: List<Int>, summary: Int = 0, focus: Int = title, keywords: String = "") =
        SettingsSearchEntry(
            id = context.resources.getResourceEntryName(title),
            title = context.getString(title),
            summary = if (summary == 0) "" else context.getString(summary),
            path = path.distinct().joinToString(" › ") { context.getString(it) },
            route = route,
            focusTitleRes = focus,
            keywords = keywords,
        )
    return listOfNotNull(
        entry(R.string.screenshot_protection, Screen.Settings.route, listOf(R.string.settings_title, R.string.security), keywords = "截图 录屏 screenshot screen capture"),
        entry(R.string.trash_bin, Screen.Settings.route, listOf(R.string.settings_title, R.string.data_management), summary = R.string.trash_enable_desc, keywords = "回收站 自动删除 垃圾箱 trash auto delete"),
        entry(R.string.clear_all_data, Screen.Settings.route, listOf(R.string.settings_title, R.string.data_management), summary = R.string.clear_all_data_subtitle, keywords = "清空数据 清空 删除 重置 erase reset"),
        entry(R.string.theme, Screen.Settings.route, listOf(R.string.settings_title, R.string.theme), keywords = "深色 浅色 纯黑 OLED dark light system"),
        entry(R.string.color_scheme, Screen.Settings.route, listOf(R.string.settings_title, R.string.theme), keywords = "配色 颜色 color palette"),
        entry(R.string.interface_scale_title, Screen.Settings.route, listOf(R.string.settings_title, R.string.theme), summary = R.string.interface_scale_description, keywords = "缩放 大小 字体 DPI scale"),
        entry(R.string.language, Screen.Settings.route, listOf(R.string.settings_title, R.string.theme), keywords = "中文 简体 繁体 English 日本語 italiano 芝士雪豹 喵喵 language"),
        entry(R.string.version, Screen.Settings.route, listOf(R.string.settings_title, R.string.about), keywords = "版本 version"),
        entry(R.string.update_check_title, Screen.Settings.route, listOf(R.string.settings_title, R.string.about), summary = R.string.update_check_subtitle, keywords = "更新 升级 update upgrade"),
        entry(R.string.developer_settings, Screen.Settings.route, listOf(R.string.settings_title, R.string.developer_settings), summary = R.string.developer_settings_subtitle, keywords = "开发者 日志 调试 developer logs debug"),
        entry(R.string.preview_features_title, Screen.Settings.route, listOf(R.string.settings_title, R.string.developer_settings), summary = R.string.preview_features_description, keywords = "预览 实验 preview"),
        entry(R.string.master_password_and_locking, Screen.MasterPasswordLockingSettings.route, listOf(R.string.settings_title, R.string.security), summary = R.string.master_password_and_locking_description, focus = 0),
        entry(R.string.permission_management_title, Screen.PermissionManagement.route, listOf(R.string.settings_title, R.string.security), summary = R.string.permission_management_subtitle, focus = 0),
        entry(R.string.sync_backup_title, Screen.SyncBackup.route, listOf(R.string.settings_title, R.string.data_management), summary = R.string.sync_backup_description, focus = 0),
        entry(R.string.autofill, Screen.AutofillSettings.route, listOf(R.string.settings_title, R.string.data_management), summary = R.string.autofill_subtitle, focus = 0),
        entry(R.string.bottom_nav_settings, Screen.BottomNavSettings.route, listOf(R.string.settings_title, R.string.theme), summary = R.string.bottom_nav_settings_entry_subtitle, focus = 0),
        entry(R.string.extensions_title, Screen.Extensions.route, listOf(R.string.settings_title, R.string.theme), summary = R.string.extensions_description, focus = 0),
        entry(R.string.page_adjust_custom_title, Screen.PageAdjustmentCustomization.route, listOf(R.string.settings_title, R.string.theme), summary = R.string.page_adjust_custom_subtitle, focus = 0),
        entry(R.string.monica_plus_title, Screen.MonicaPlus.route, listOf(R.string.settings_title, R.string.settings_title), summary = R.string.monica_plus_card_desc, focus = 0),
        entry(R.string.biometric_unlock, Screen.MasterPasswordLockingSettings.route, listOf(R.string.settings_title, R.string.master_password_and_locking)),
        entry(R.string.auto_lock, Screen.MasterPasswordLockingSettings.route, listOf(R.string.settings_title, R.string.master_password_and_locking)),
        entry(R.string.reset_master_password, Screen.MasterPasswordLockingSettings.route, listOf(R.string.settings_title, R.string.master_password_and_locking), summary = R.string.reset_password_description),
        entry(R.string.security_questions, Screen.MasterPasswordLockingSettings.route, listOf(R.string.settings_title, R.string.master_password_and_locking), summary = R.string.security_questions_description),
        entry(R.string.autofill_protection_entry_title, Screen.AutofillSettings.route, listOf(R.string.settings_title, R.string.autofill), summary = R.string.autofill_protection_entry_desc),
        entry(R.string.autofill_v2_set_system_service, Screen.AutofillSettings.route, listOf(R.string.settings_title, R.string.autofill), summary = R.string.autofill_v2_set_system_service_desc),
        entry(R.string.autofill_system_passkey_settings, Screen.AutofillSettings.route, listOf(R.string.settings_title, R.string.autofill), summary = R.string.autofill_system_passkey_settings_desc),
        entry(R.string.ime_manage_input_methods, Screen.AutofillSettings.route, listOf(R.string.settings_title, R.string.autofill), summary = R.string.ime_manage_input_methods_desc, keywords = "键盘 PIN 数字 keyboard input method"),
        entry(R.string.ime_scramble_pin_title, Screen.AutofillSettings.route, listOf(R.string.settings_title, R.string.autofill), summary = R.string.ime_scramble_pin_description, keywords = "数字键随机 PIN洗牌 键盘 PIN 数字 keyboard input method"),
        entry(R.string.ime_hide_pin_preview_title, Screen.AutofillSettings.route, listOf(R.string.settings_title, R.string.autofill), summary = R.string.ime_hide_pin_preview_description, keywords = "隐藏预览 隐藏按键预览 按键预览 键盘 PIN 数字 keyboard input method"),
        entry(R.string.autofill_v2_enable_service, Screen.AutofillSettings.route, listOf(R.string.settings_title, R.string.autofill), summary = R.string.autofill_v2_enable_service_desc),
        entry(R.string.autofill_active_fill_notification_title, Screen.AutofillSettings.route, listOf(R.string.settings_title, R.string.autofill), summary = R.string.autofill_active_fill_notification_desc),
        entry(R.string.autofill_auth_required, Screen.AutofillSettings.route, listOf(R.string.settings_title, R.string.autofill), summary = R.string.autofill_auth_required_desc),
        entry(R.string.autofill_v2_strict_match, Screen.AutofillSettings.route, listOf(R.string.settings_title, R.string.autofill), summary = R.string.autofill_v2_strict_match_desc),
        entry(R.string.autofill_v2_subdomain_match, Screen.AutofillSettings.route, listOf(R.string.settings_title, R.string.autofill), summary = R.string.autofill_v2_subdomain_match_desc),
        entry(R.string.autofill_v2_respect_off, Screen.AutofillSettings.route, listOf(R.string.settings_title, R.string.autofill), summary = R.string.autofill_v2_respect_off_desc),
        entry(R.string.autofill_inline_suggestions, Screen.AutofillSettings.route, listOf(R.string.settings_title, R.string.autofill), summary = R.string.autofill_inline_suggestions_desc),
        entry(R.string.password_suggestion_title, Screen.AutofillSettings.route, listOf(R.string.settings_title, R.string.autofill), summary = R.string.autofill_password_suggestion_setting_desc),
        entry(R.string.autofill_save_enable, Screen.AutofillSettings.route, listOf(R.string.settings_title, R.string.autofill), summary = R.string.autofill_save_enable_desc),
        entry(R.string.autofill_save_update_duplicate, Screen.AutofillSettings.route, listOf(R.string.settings_title, R.string.autofill), summary = R.string.autofill_save_update_duplicate_desc),
        entry(R.string.autofill_save_show_notification, Screen.AutofillSettings.route, listOf(R.string.settings_title, R.string.autofill), summary = R.string.autofill_save_show_notification_desc),
        entry(R.string.autofill_save_smart_title, Screen.AutofillSettings.route, listOf(R.string.settings_title, R.string.autofill), summary = R.string.autofill_save_smart_title_desc),
        entry(R.string.autofill_save_app_info, Screen.AutofillSettings.route, listOf(R.string.settings_title, R.string.autofill), summary = R.string.autofill_save_app_info_desc),
        entry(R.string.autofill_save_website_info, Screen.AutofillSettings.route, listOf(R.string.settings_title, R.string.autofill), summary = R.string.autofill_save_website_info_desc),
        entry(R.string.autofill_show_otp_notification, Screen.AutofillSettings.route, listOf(R.string.settings_title, R.string.autofill), summary = R.string.autofill_show_otp_notification_desc),
        entry(R.string.autofill_auto_copy_otp, Screen.AutofillSettings.route, listOf(R.string.settings_title, R.string.autofill), summary = R.string.autofill_auto_copy_otp_desc),
        entry(R.string.re_quick_init_title, Screen.Extensions.route, listOf(R.string.settings_title, R.string.extensions_title), summary = R.string.re_quick_init_desc),
        entry(R.string.smart_deduplication, Screen.Extensions.route, listOf(R.string.settings_title, R.string.extensions_title), summary = R.string.smart_deduplication_desc),
        entry(R.string.password_detail_security_analysis_title, Screen.Extensions.route, listOf(R.string.settings_title, R.string.extensions_title), summary = R.string.password_detail_security_analysis_desc),
        entry(R.string.steam_mini_profile_background_title, Screen.Extensions.route, listOf(R.string.settings_title, R.string.extensions_title), summary = R.string.steam_mini_profile_background_description),
        entry(R.string.haptic_feedback, Screen.Extensions.route, listOf(R.string.settings_title, R.string.extensions_title), summary = R.string.haptic_feedback_description),
        if (isPlusActivated) entry(R.string.validator_vibration, Screen.Extensions.route, listOf(R.string.settings_title, R.string.extensions_title), summary = R.string.validator_vibration_description) else null,
        if (isPlusActivated) entry(R.string.copy_next_code_when_expiring, Screen.Extensions.route, listOf(R.string.settings_title, R.string.extensions_title), summary = R.string.copy_next_code_when_expiring_description) else null,
        entry(R.string.clipboard_auto_clear_title, Screen.Extensions.route, listOf(R.string.settings_title, R.string.extensions_title), summary = R.string.clipboard_auto_clear_description, keywords = "剪贴板 自动清理 自动清除 clipboard clear"),
        entry(R.string.swipe_selection_mode, Screen.Extensions.route, listOf(R.string.settings_title, R.string.extensions_title), summary = R.string.swipe_selection_mode_desc),
        entry(R.string.webdav_backup, Screen.SyncBackup.route, listOf(R.string.settings_title, R.string.sync_backup_title), summary = R.string.webdav_backup_description),
        entry(R.string.onedrive_backup_title, Screen.SyncBackup.route, listOf(R.string.settings_title, R.string.sync_backup_title), summary = R.string.onedrive_backup_description),
        entry(R.string.sync_backup_bitwarden_sync_title, Screen.SyncBackup.route, listOf(R.string.settings_title, R.string.sync_backup_title), summary = R.string.sync_backup_bitwarden_sync_desc),
        entry(R.string.dedup_engine_title, Screen.SyncBackup.route, listOf(R.string.settings_title, R.string.sync_backup_title), summary = R.string.dedup_engine_entry_desc),
        entry(R.string.local_keepass_database, Screen.SyncBackup.route, listOf(R.string.settings_title, R.string.sync_backup_title), summary = R.string.local_keepass_database_description),
        entry(R.string.mdbx_ui_manager_entry_title, Screen.SyncBackup.route, listOf(R.string.settings_title, R.string.sync_backup_title), summary = R.string.mdbx_ui_manager_entry_description),
        entry(R.string.export_data, Screen.SyncBackup.route, listOf(R.string.settings_title, R.string.sync_backup_title), summary = R.string.export_data_description),
        entry(R.string.import_data, Screen.SyncBackup.route, listOf(R.string.settings_title, R.string.sync_backup_title), summary = R.string.import_data_description),
        entry(R.string.vault_v2_hierarchical_layout_title, Screen.PageAdjustmentCustomization.route, listOf(R.string.settings_title, R.string.page_adjust_custom_title), summary = R.string.vault_v2_hierarchical_layout_desc),
        entry(R.string.vault_overview_enabled_title, Screen.PageAdjustmentCustomization.route, listOf(R.string.settings_title, R.string.page_adjust_custom_title), summary = R.string.vault_overview_enabled_desc),
        entry(R.string.wallet_stack_loop_title, Screen.PageAdjustmentCustomization.route, listOf(R.string.settings_title, R.string.page_adjust_custom_title), summary = R.string.wallet_stack_loop_desc),
        entry(R.string.separate_username_account_title, Screen.PasswordFieldCustomization.route, listOf(R.string.settings_title, R.string.page_adjust_custom_title, R.string.password_field_customization_title), summary = R.string.separate_username_account_desc),
        entry(R.string.autofill_domain_strategy_title, Screen.AutofillSettings.route, listOf(R.string.settings_title, R.string.autofill)),
        entry(R.string.autofill_otp_notification_duration, Screen.AutofillSettings.route, listOf(R.string.settings_title, R.string.autofill), summary = R.string.autofill_otp_notification_duration_desc),
        entry(R.string.autofill_blacklist_manage, Screen.AutofillSettings.route, listOf(R.string.settings_title, R.string.autofill)),
        entry(R.string.autofill_blocked_fields_manage, Screen.AutofillSettings.route, listOf(R.string.settings_title, R.string.autofill)),
        entry(R.string.autofill_save_blocked_targets_manage, Screen.AutofillSettings.route, listOf(R.string.settings_title, R.string.autofill)),
        entry(R.string.autofill_v2_default_scope_title, Screen.AutofillSettings.route, listOf(R.string.settings_title, R.string.autofill), summary = R.string.autofill_v2_default_scope_desc),
        entry(R.string.password_card_display_mode_title, Screen.Extensions.route, listOf(R.string.settings_title, R.string.extensions_title)),
        entry(R.string.password_list_customization_title, Screen.PasswordListCustomization.route, listOf(R.string.settings_title, R.string.page_adjust_custom_title), summary = R.string.password_list_customization_subtitle, focus = 0),
        entry(R.string.password_card_adjust_title, Screen.PasswordCardAdjustment.route, listOf(R.string.settings_title, R.string.page_adjust_custom_title), summary = R.string.password_card_adjust_subtitle, focus = 0),
        entry(R.string.authenticator_card_adjust_title, Screen.AuthenticatorCardAdjustment.route, listOf(R.string.settings_title, R.string.page_adjust_custom_title), summary = R.string.authenticator_card_adjust_subtitle, focus = 0),
        entry(R.string.password_field_customization_title, Screen.PasswordFieldCustomization.route, listOf(R.string.settings_title, R.string.page_adjust_custom_title), summary = R.string.extensions_password_field_customization_desc, focus = 0),
        entry(R.string.icon_settings_title, Screen.IconSettings.route, listOf(R.string.settings_title, R.string.page_adjust_custom_title), summary = R.string.icon_settings_subtitle, focus = 0),
        entry(R.string.icon_settings_app_icon_title, Screen.IconSettings.route, listOf(R.string.settings_title, R.string.page_adjust_custom_title, R.string.icon_settings_title), summary = R.string.launcher_icon_selection_description, keywords = "桌面 图标 Grok bot 雪豹 默认 主应用 app launcher icon"),
        entry(R.string.icon_settings_master_switch, Screen.IconSettings.route, listOf(R.string.settings_title, R.string.page_adjust_custom_title, R.string.icon_settings_title), summary = R.string.icon_settings_master_desc, keywords = "图标 开关"),
        entry(R.string.icon_settings_page_switches_title, Screen.IconSettings.route, listOf(R.string.settings_title, R.string.page_adjust_custom_title, R.string.icon_settings_title), summary = R.string.icon_settings_page_switches_desc, keywords = "密码 验证器 通行密钥 图标"),
        entry(R.string.icon_settings_unmatched_strategy_title, Screen.IconSettings.route, listOf(R.string.settings_title, R.string.page_adjust_custom_title, R.string.icon_settings_title), keywords = "未匹配 图标 字母 隐藏"),
        entry(R.string.icon_settings_priority_title, Screen.IconSettings.route, listOf(R.string.settings_title, R.string.page_adjust_custom_title, R.string.icon_settings_title), summary = R.string.icon_settings_priority_desc, keywords = "图标 优先级"),
        entry(R.string.icon_settings_source_title, Screen.IconSettings.route, listOf(R.string.settings_title, R.string.page_adjust_custom_title, R.string.icon_settings_title), summary = R.string.icon_settings_source_desc, keywords = "图标 来源"),
        entry(R.string.password_page_aggregate_switch_title, Screen.PasswordListCustomization.route, listOf(R.string.settings_title, R.string.page_adjust_custom_title, R.string.password_list_customization_title), keywords = "新建 添加按钮 add button menu"),
        entry(R.string.password_list_quick_filters_switch_title, Screen.PasswordListCustomization.route, listOf(R.string.settings_title, R.string.page_adjust_custom_title, R.string.password_list_customization_title)),
        entry(R.string.password_list_category_quick_filters_switch_title, Screen.PasswordListCustomization.route, listOf(R.string.settings_title, R.string.page_adjust_custom_title, R.string.password_list_customization_title)),
        entry(R.string.password_list_quick_folder_path_banner_switch_title, Screen.PasswordListCustomization.route, listOf(R.string.settings_title, R.string.page_adjust_custom_title, R.string.password_list_customization_title)),
        entry(R.string.password_list_system_back_to_parent_folder_switch_title, Screen.PasswordListCustomization.route, listOf(R.string.settings_title, R.string.page_adjust_custom_title, R.string.password_list_customization_title)),
        entry(R.string.password_list_quick_access_switch_title, Screen.PasswordListCustomization.route, listOf(R.string.settings_title, R.string.page_adjust_custom_title, R.string.password_list_customization_title)),
        entry(R.string.password_card_show_authenticator_title, Screen.PasswordCardAdjustment.route, listOf(R.string.settings_title, R.string.page_adjust_custom_title, R.string.password_card_adjust_title)),
        entry(R.string.password_card_hide_other_content_when_authenticator_title, Screen.PasswordCardAdjustment.route, listOf(R.string.settings_title, R.string.page_adjust_custom_title, R.string.password_card_adjust_title)),
        entry(R.string.group_mode_menu_title, Screen.PasswordCardAdjustment.route, listOf(R.string.settings_title, R.string.page_adjust_custom_title, R.string.password_card_adjust_title)),
        entry(R.string.stack_mode_menu_title, Screen.PasswordCardAdjustment.route, listOf(R.string.settings_title, R.string.page_adjust_custom_title, R.string.password_card_adjust_title)),
        entry(R.string.website_stack_match_mode_title, Screen.PasswordCardAdjustment.route, listOf(R.string.settings_title, R.string.page_adjust_custom_title, R.string.password_card_adjust_title)),
        entry(R.string.authenticator_card_display_content_title, Screen.AuthenticatorCardAdjustment.route, listOf(R.string.settings_title, R.string.page_adjust_custom_title, R.string.authenticator_card_adjust_title)),
        entry(R.string.unified_progress_bar_title, Screen.AuthenticatorCardAdjustment.route, listOf(R.string.settings_title, R.string.page_adjust_custom_title, R.string.authenticator_card_adjust_title)),
        entry(R.string.validator_progress_bar_style, Screen.AuthenticatorCardAdjustment.route, listOf(R.string.settings_title, R.string.page_adjust_custom_title, R.string.authenticator_card_adjust_title)),
        entry(R.string.smooth_progress_bar_title, Screen.AuthenticatorCardAdjustment.route, listOf(R.string.settings_title, R.string.page_adjust_custom_title, R.string.authenticator_card_adjust_title)),
    )
}
