"""Generate the supported Unicode Emoji sequences (Unicode 17.0, Unicode-3.0)."""

from pathlib import Path
from urllib.request import urlopen

VERSION = "17.0.0"
ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "app/src/main/java/takagi/ru/monica/ui/icons/EmojiUnicodeSequences.kt"
PROPERTIES = {"RGI_Emoji_ZWJ_Sequence", "RGI_Emoji_Flag_Sequence", "RGI_Emoji_Tag_Sequence"}


def main():
    sequences = set()
    for filename in ("emoji-sequences.txt", "emoji-zwj-sequences.txt"):
        url = f"https://www.unicode.org/Public/{VERSION}/emoji/{filename}"
        with urlopen(url, timeout=30) as response:
            contents = response.read().decode("utf-8")
        for line in contents.splitlines():
            fields = line.split("#", 1)[0].split(";")
            if len(fields) < 2 or fields[1].strip() not in PROPERTIES:
                continue
            # Presentation selectors are optional; the caller validates their position.
            sequence = "".join(chr(int(cp, 16)) for cp in fields[0].split() if cp != "FE0F")
            sequences.add(sequence)
    assert len(sequences) > 1800
    header = f"""package takagi.ru.monica.ui.icons

// Generated by scripts/update_emoji_sequences.py from Unicode {VERSION}:
// https://www.unicode.org/Public/{VERSION}/emoji/emoji-sequences.txt
// https://www.unicode.org/Public/{VERSION}/emoji/emoji-zwj-sequences.txt
// Copyright © 2025 Unicode, Inc. SPDX-License-Identifier: Unicode-3.0
// License: docs/licenses/unicode-emoji-license.txt

internal fun isRegisteredEmojiSequence(value: String): Boolean =
    value.replace("\\uFE0F", "") in REGISTERED_EMOJI_SEQUENCES

private val REGISTERED_EMOJI_SEQUENCES = setOf(
"""
    TARGET.write_text(header + "".join(f'    "{value}",\n' for value in sorted(sequences)) + ")\n", encoding="utf-8")
    print(f"Generated {len(sequences)} registered Emoji sequences in {TARGET.name}")


if __name__ == "__main__":
    main()
