package takagi.ru.monica.repository

import org.json.JSONArray
import org.json.JSONObject
import takagi.ru.monica.credentialexchange.ImportDestinationKind

internal suspend fun managerDetailPayload(repo: DatabaseManagerRepository, location: DatabaseManagerLocation, row: MdbxStructureNode): String {
    if (location.database.kind == ImportDestinationKind.MDBX) {
        repo.mdbx.requireRoomMirrorAllowed(location.database.databaseId)
        return repo.mdbx.nativeObject(location.database.databaseId, row.id).payload
    }
    val id = row.id.substringAfter(':').toLong()
    return when (row.id.substringBefore(':')) {
        "password" -> {
            val value = requireNotNull(repo.db.passwordEntryDao().getPasswordEntryById(id))
            check(location.database.contains(value))
            val fields = repo.db.customFieldDao().getFieldsByEntryIds(listOf(id))
            val readable = value.copy(password = repo.security.decryptDataIfMonicaCiphertext(value.password),
                authenticatorKey = repo.security.decryptDataIfMonicaCiphertext(value.authenticatorKey),
                creditCardNumber = repo.security.decryptDataIfMonicaCiphertext(value.creditCardNumber),
                creditCardCVV = repo.security.decryptDataIfMonicaCiphertext(value.creditCardCVV))
            JSONObject()
                .put("id", readable.id)
                .put("title", readable.title)
                .put("website", readable.website)
                .put("username", readable.username)
                .put("password", readable.password)
                .put("notes", readable.notes)
                .put("createdAt", readable.createdAt.time)
                .put("updatedAt", readable.updatedAt.time)
                .put("isFavorite", readable.isFavorite)
                .put("sortOrder", readable.sortOrder)
                .put("isGroupCover", readable.isGroupCover)
                .put("appPackageName", readable.appPackageName)
                .put("appName", readable.appName)
                .put("email", readable.email)
                .put("phone", readable.phone)
                .put("addressLine", readable.addressLine)
                .put("city", readable.city)
                .put("state", readable.state)
                .put("zipCode", readable.zipCode)
                .put("country", readable.country)
                .put("creditCardNumber", readable.creditCardNumber)
                .put("creditCardHolder", readable.creditCardHolder)
                .put("creditCardExpiry", readable.creditCardExpiry)
                .put("creditCardCVV", readable.creditCardCVV)
                .put("categoryId", readable.categoryId)
                .put("boundNoteId", readable.boundNoteId)
                .put("keepassDatabaseId", readable.keepassDatabaseId)
                .put("keepassGroupPath", readable.keepassGroupPath)
                .put("keepassEntryUuid", readable.keepassEntryUuid)
                .put("keepassGroupUuid", readable.keepassGroupUuid)
                .put("mdbxDatabaseId", readable.mdbxDatabaseId)
                .put("mdbxFolderId", readable.mdbxFolderId)
                .put("authenticatorKey", readable.authenticatorKey)
                .put("passkeyBindings", readable.passkeyBindings)
                .put("sshKeyData", readable.sshKeyData)
                .put("loginType", readable.loginType)
                .put("ssoProvider", readable.ssoProvider)
                .put("ssoRefEntryId", readable.ssoRefEntryId)
                .put("wifiMetadata", readable.wifiMetadata)
                .put("customIconType", readable.customIconType)
                .put("customIconValue", readable.customIconValue)
                .put("customIconUpdatedAt", readable.customIconUpdatedAt)
                .put("isDeleted", readable.isDeleted)
                .put("deletedAt", readable.deletedAt?.time)
                .put("isArchived", readable.isArchived)
                .put("archivedAt", readable.archivedAt?.time)
                .put("replicaGroupId", readable.replicaGroupId)
                .put("passwordGroupId", readable.passwordGroupId)
                .put("bitwardenVaultId", readable.bitwardenVaultId)
                .put("bitwardenCipherId", readable.bitwardenCipherId)
                .put("bitwardenFolderId", readable.bitwardenFolderId)
                .put("bitwardenRevisionDate", readable.bitwardenRevisionDate)
                .put("bitwardenCipherType", readable.bitwardenCipherType)
                .put("bitwardenLocalModified", readable.bitwardenLocalModified)
                .put("custom_fields", JSONArray().apply { fields.forEach { put(JSONObject().put("title", it.title).put("value", it.value).put("isProtected", it.isProtected).put("sortOrder", it.sortOrder)) } }).toString()
        }
        "item" -> {
            val value = requireNotNull(repo.db.secureItemDao().getItemById(id)); check(location.database.contains(value))
            val readable = value.copy(itemData = repo.security.decryptDataIfMonicaCiphertext(value.itemData))
            JSONObject()
                .put("id", readable.id)
                .put("itemType", readable.itemType.name)
                .put("title", readable.title)
                .put("notes", readable.notes)
                .put("isFavorite", readable.isFavorite)
                .put("sortOrder", readable.sortOrder)
                .put("createdAt", readable.createdAt.time)
                .put("updatedAt", readable.updatedAt.time)
                .put("itemData", readable.itemData)
                .put("imagePaths", readable.imagePaths)
                .put("categoryId", readable.categoryId)
                .put("keepassDatabaseId", readable.keepassDatabaseId)
                .put("keepassGroupPath", readable.keepassGroupPath)
                .put("keepassEntryUuid", readable.keepassEntryUuid)
                .put("keepassGroupUuid", readable.keepassGroupUuid)
                .put("mdbxDatabaseId", readable.mdbxDatabaseId)
                .put("mdbxFolderId", readable.mdbxFolderId)
                .put("isDeleted", readable.isDeleted)
                .put("deletedAt", readable.deletedAt?.time)
                .put("replicaGroupId", readable.replicaGroupId)
                .put("bitwardenVaultId", readable.bitwardenVaultId)
                .put("bitwardenCipherId", readable.bitwardenCipherId)
                .put("bitwardenFolderId", readable.bitwardenFolderId)
                .put("bitwardenRevisionDate", readable.bitwardenRevisionDate)
                .put("bitwardenLocalModified", readable.bitwardenLocalModified)
                .put("syncStatus", readable.syncStatus).toString()
        }
        "passkey" -> {
            val value = requireNotNull(repo.db.passkeyDao().getPasskeyByRecordId(id)); check(location.database.contains(value))
            JSONObject().put("rp_id", value.rpId).put("username", value.userName).put("credential_id", value.credentialId).put("notes", value.notes).toString()
        }
        else -> error("Unsupported entry")
    }
}
